name: Deploy Frontend to Azure Web App

on:
  workflow_dispatch:
  # Push trigger comentado para evitar deploy automático no primeiro commit
  # Descomente as linhas abaixo se quiser deploy automático em futuros pushes:
  # push:
  #   branches:
  #     - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Create production environment file
        working-directory: ./frontend
        run: |
          echo "NEXT_PUBLIC_API_URL=https://expandev-05.azurewebsites.net/api/v1" > .env.production
          cat .env.production

      - name: Update next.config.mjs with backend URL
        working-directory: ./frontend
        run: |
          cat > next.config.mjs << 'EOF'
          /** @type {import('next').NextConfig} */
          const nextConfig = {
            output: 'standalone',
            async rewrites() {
              return [
                {
                  source: '/api/:path*',
                  destination: 'https://expandev-05.azurewebsites.net/api/:path*',
                },
              ];
            },
          };
          
          export default nextConfig;
          EOF

      - name: npm install and build
        working-directory: ./frontend
        run: |
          npm install
          NEXT_PUBLIC_API_URL=https://expandev-05.azurewebsites.net/api/v1 npm run build
          cp -r public .next/standalone/
          cp -r .next/static .next/standalone/.next/

      - name: Zip artifact for deployment
        run: |
          mkdir -p deployment
          cp -r frontend/.next/standalone/* deployment/
          cd deployment
          zip -r ../release.zip .

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'expandev-06'
          package: .
          startup-command: 'node .next/standalone/server.js'